FROM nginx

ENV APP_PATH="/var/www/lotus"

WORKDIR $APP_PATH

RUN mkdir log

COPY public public/

#COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf
#COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf

COPY docker/nginx/default.conf /tmp/docker_example.nginx
RUN envsubst '$APP_PATH' < /tmp/docker_example.nginx > /etc/nginx/conf.d/default.conf


EXPOSE 80

CMD ["nginx","-g","daemon off;"]
